# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

layout_with_coulomb_Cpp <- function(pniter, pvcount, pecount, maxdelta, parea, pcoolexp, prepulserad, pcoulombrad, Ef, Et, W, sizes, xInit, yInit, Cx, Cy, digits) {
    .Call(`_qgraph_layout_with_coulomb_Cpp`, pniter, pvcount, pecount, maxdelta, parea, pcoolexp, prepulserad, pcoulombrad, Ef, Et, W, sizes, xInit, yInit, Cx, Cy, digits)
}

qgraph_layout_Cpp <- function(pniter, pvcount, pecount, maxdelta, parea, pcoolexp, prepulserad, Ef, Et, W, xInit, yInit, Cx, Cy, digits) {
    .Call(`_qgraph_qgraph_layout_Cpp`, pniter, pvcount, pecount, maxdelta, parea, pcoolexp, prepulserad, Ef, Et, W, xInit, yInit, Cx, Cy, digits)
}

